server:
  port: 8080

spring:
  application:
    name: game-service
  data:
    mongodb:
      uri: mongodb://admin:password123@mongodb:27017/catalogoJuegos?authSource=admin
      
logging:
  level:
    com.gamestore.game: DEBUG
    org.springframework.data.mongodb: DEBUG