version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: catalogoJuegos
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - game-network

  game-service:
    build: ./game-service
    container_name: game-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password123@mongodb:27017/catalogoJuegos?authSource=admin
    networks:
      - game-network

  frontend:
    build: ./Frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - game-service
    networks:
      - game-network

volumes:
  mongodb_data:

networks:
  game-network:
    driver: bridge