server:
  port: 8081
  servlet:
    context-path: /api/users

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://pier:7226@clusterpirry.8cwgf.mongodb.net/bookswap_user?retryWrites=true&w=majority&appName=ClusterPirry
      auto-index-creation: true

auth-service:
  url: http://auth-service:8080/api/auth

logging:
  level:
    root: INFO
    com.bookswap: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: WARN
    org.mongodb.driver: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight(%-5level) %cyan(%-40.40logger{39}) : %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    enabled: true
  show-actuator: true
  use-fqn: true