server:
  port: 8080

spring:
  application:
    name: game-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/catalogoJuegos
      
logging:
  level:
    com.gamestore.game: DEBUG
    org.springframework.data.mongodb: DEBUG